# Generated by Django 6.1.1 on 2026-09-26 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='The address or phone number it was sent to.', max_length=254, verbose_name='recipient')),
                ('subject', models.CharField(help_text="The email's subject, or 'Text message'.", max_length=255, verbose_name='subject')),
                ('body', models.TextField(help_text='The message as it would have been sent.', verbose_name='body')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When it was sent. The outbox lists the newest first.', verbose_name='sent at')),
            ],
            options={
                'verbose_name': 'sent message',
                'verbose_name_plural': 'sent messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='The number in international format, for example +4915112345678.', max_length=32, unique=True, verbose_name='number')),
                ('verified', models.BooleanField(default=False, help_text='Whether the person has entered the code sent to this number.', verbose_name='verified')),
                ('user', models.OneToOneField(help_text='The account this number belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'phone number',
                'verbose_name_plural': 'phone numbers',
            },
        ),
    ]
