# Generated by Django 6.1.1 on 2026-09-26 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='The number in international format, for example +4915112345678.', max_length=32, unique=True, verbose_name='number')),
                ('verified', models.BooleanField(default=False, help_text='Whether the person has entered the code sent to this number.', verbose_name='verified')),
                ('user', models.OneToOneField(help_text='The account this number belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'phone number',
                'verbose_name_plural': 'phone numbers',
            },
        ),
    ]
